
package com._3line.gravity.freedom._3linecms.saopservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerAccountServiceService", targetNamespace = "http://service.arsblue.rs", wsdlLocation = "http://10.2.2.28:9080/LoadCustomerDataWS/services/CustomerAccountService/wsdl/CustomerAccountService.wsdl")
public class CustomerAccountServiceService
    extends Service
{

    private final static URL CUSTOMERACCOUNTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERACCOUNTSERVICESERVICE_EXCEPTION;
    private final static QName CUSTOMERACCOUNTSERVICESERVICE_QNAME = new QName("http://service.arsblue.rs", "CustomerAccountServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.2.2.28:9080/LoadCustomerDataWS/services/CustomerAccountService/wsdl/CustomerAccountService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERACCOUNTSERVICESERVICE_WSDL_LOCATION = url;
        CUSTOMERACCOUNTSERVICESERVICE_EXCEPTION = e;
    }

    public CustomerAccountServiceService() {
        super(__getWsdlLocation(), CUSTOMERACCOUNTSERVICESERVICE_QNAME);
    }

    public CustomerAccountServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERACCOUNTSERVICESERVICE_QNAME, features);
    }

    public CustomerAccountServiceService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERACCOUNTSERVICESERVICE_QNAME);
    }

    public CustomerAccountServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERACCOUNTSERVICESERVICE_QNAME, features);
    }

    public CustomerAccountServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerAccountServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerAccountService
     */
    @WebEndpoint(name = "CustomerAccountService")
    public CustomerAccountService getCustomerAccountService() {
        return super.getPort(new QName("http://service.arsblue.rs", "CustomerAccountService"), CustomerAccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerAccountService
     */
    @WebEndpoint(name = "CustomerAccountService")
    public CustomerAccountService getCustomerAccountService(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.arsblue.rs", "CustomerAccountService"), CustomerAccountService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERACCOUNTSERVICESERVICE_EXCEPTION!= null) {
            throw CUSTOMERACCOUNTSERVICESERVICE_EXCEPTION;
        }
        return CUSTOMERACCOUNTSERVICESERVICE_WSDL_LOCATION;
    }

}
