
package com._3line.gravity.freedom._3linecms.saopservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerAccountService", targetNamespace = "http://service.arsblue.rs")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerAccountService {


    /**
     * 
     * @param xmlString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "sendDataTo3Line")
    @WebResult(name = "sendDataTo3LineReturn", targetNamespace = "")
    @RequestWrapper(localName = "sendDataTo3Line", targetNamespace = "http://service.arsblue.rs", className = "com._3line.app.core.service._3linecms.SendDataTo3Line")
    @ResponseWrapper(localName = "sendDataTo3LineResponse", targetNamespace = "http://service.arsblue.rs", className = "com._3line.app.core.service._3linecms.SendDataTo3LineResponse")
    String sendDataTo3Line(
            @WebParam(name = "xmlString", targetNamespace = "")
                    String xmlString);

}
