
package com._3line.gravity.freedom._3linecms.quicktellercms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QuickTellerCMService", targetNamespace = "http://service.arius.rs")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuickTellerCMService {


    /**
     * 
     * @param xmlString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "validatePayment")
    @WebResult(name = "validatePaymentReturn", targetNamespace = "")
    @RequestWrapper(localName = "validatePayment", targetNamespace = "http://service.arius.rs", className = "com._3line.app.core.service._3linecms.quicktellercms.ValidatePayment")
    @ResponseWrapper(localName = "validatePaymentResponse", targetNamespace = "http://service.arius.rs", className = "com._3line.app.core.service._3linecms.quicktellercms.ValidatePaymentResponse")
    String validatePayment(
            @WebParam(name = "xmlString", targetNamespace = "")
                    String xmlString);

    /**
     * 
     * @param xmlString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "executePayment")
    @WebResult(name = "executePaymentReturn", targetNamespace = "")
    @RequestWrapper(localName = "executePayment", targetNamespace = "http://service.arius.rs", className = "com._3line.app.core.service._3linecms.quicktellercms.ExecutePayment")
    @ResponseWrapper(localName = "executePaymentResponse", targetNamespace = "http://service.arius.rs", className = "com._3line.app.core.service._3linecms.quicktellercms.ExecutePaymentResponse")
    String executePayment(
            @WebParam(name = "xmlString", targetNamespace = "")
                    String xmlString);

}
